import {PATHS,SEASONS,season,cycleGoal,rootReward,wish,permanentFactor} from './growth.js';
import {format} from './economy.js';
import {icon} from './icons.js';
export function journeyCards(s){const w=wish(s),path=PATHS.find(p=>p.id===s.path),goal=cycleGoal(s);return `
<article class="journey-intro"><span class="eyebrow">LE CARNET DU VEILLEUR · CHAPITRE ${format(s.cycles+1)}</span><h3>Tout commence par une graine.</h3><p>Les racines se souviennent de chaque forêt. Moko emporte ces souvenirs vers un nouveau jardin, aussi longtemps que vous le souhaitez.</p><div class="root-summary">${icon('leaf')} ${format(s.roots)} racines éternelles <strong>×${format(permanentFactor(s),true)} production</strong></div></article>
<div class="journey-label">${path?'Votre voie · jusqu’à la prochaine renaissance':'Choisir la prochaine couleur des bois'}</div>
${PATHS.map(p=>`<button class="path-card ${s.path===p.id?'chosen':''}" data-path="${p.id}" ${s.path?'disabled':''}><span class="path-emblem" style="--path-color:${p.color}">${icon(p.icon)}</span><span><strong>${p.name}</strong><small>${p.description}</small></span>${s.path===p.id?icon('check'):icon('arrow')}</button>`).join('')}
<article class="wish-card"><div class="journey-label">SOUHAIT ${format(s.wishes+1)} · SANS LIMITE DE TEMPS</div><h3>${w.title}</h3><p>${w.hint}</p><progress id="wish-progress" max="${w.goal}" value="${Math.min(w.goal,w.value)}"></progress><div class="journey-footer"><span id="wish-count">${format(w.value)} / ${format(w.goal)}</span><button class="buy-button" data-wish ${w.value<w.goal?'disabled':''}>${icon('leaf')} +1 racine</button></div></article>
<article class="rebirth-card"><div class="journey-label">UN JARDIN APRÈS L’AUTRE</div><h3>Offrir une forêt au monde</h3><p>À ${format(goal)} lueurs créées, recommencez avec des racines qui accélèrent tous vos futurs jardins. Vos amis et souvenirs restent avec Moko.</p><progress id="cycle-progress" max="${goal}" value="${Math.min(goal,s.earned)}"></progress><div class="journey-footer"><span id="cycle-count">${format(s.earned)} / ${format(goal)}</span><button class="buy-button" data-rebirth ${s.earned<goal?'disabled':''}>Essaimer ${icon('arrow')}</button></div></article>`;}
export function refreshJourney(s){const w=wish(s),goal=cycleGoal(s);for(const [id,val]of [['wish-progress',Math.min(w.goal,w.value)],['cycle-progress',Math.min(goal,s.earned)]]){const el=document.getElementById(id);if(el)el.value=val;}const wc=document.getElementById('wish-count'),cc=document.getElementById('cycle-count');if(wc)wc.textContent=`${format(Math.min(w.value,w.goal))} / ${format(w.goal)}`;if(cc)cc.textContent=`${format(Math.min(s.earned,goal))} / ${format(goal)}`;const wb=document.querySelector('[data-wish]'),rb=document.querySelector('[data-rebirth]');if(wb)wb.disabled=w.value<w.goal;if(rb)rb.disabled=s.earned<goal;}
export function journeyBadge(s){return `${SEASONS[season(s)]} · Jardin ${format(s.cycles+1)}`;}
export function rebirthDescription(s){return `Moko emportera ${rootReward(s)} nouvelle${rootReward(s)>1?'s':''} racine${rootReward(s)>1?'s':''}. Les lueurs, niveaux, voie et spécialisations de ce jardin repartent de zéro. Vos compagnons, souvenirs et ${s.roots} racines sont conservés. Vous pourrez choisir une autre voie.`;}
