import {PATHS,growthFactor,permanentFactor,season,offlineLimit} from './growth.js';
import {journeyCards,refreshJourney,journeyBadge,rebirthDescription} from './journey-ui.js';
import {mount} from './ui.js';
import {icon} from './icons.js';
import {RefugeScene} from './refuge-scene.js';
import {SoftAudio} from './audio.js';
import {SAVE_KEY,MAX_OFFLINE,GARDEN,FRIENDS,MEMORIES,freshState,parseSave,rate,bonus,price,settle,buyGarden,invite,claim,format,duration,choosePath,specialize,buyMany,claimWish,rebirth} from './economy.js';
import './style.css';

mount();const $=id=>document.getElementById(id),PREF_KEY='moko-pocket-preferences-v1';let raw=null,prefs={reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,theme:'auto'};try{raw=localStorage.getItem(SAVE_KEY);const p=JSON.parse(localStorage.getItem(PREF_KEY)||'null');if(p){prefs.reduced=typeof p.reduced==='boolean'?p.reduced:prefs.reduced;prefs.theme=['auto','day','night'].includes(p.theme)?p.theme:'auto';}}catch{}
let state=parseSave(raw)||freshState(),firstVisit=!parseSave(raw),activeTab='garden',buyAmount=1,pendingImport=null,pendingOffline=null,toastTimer,heartTimer,installPrompt=null,ready=false,lastSave=Date.now(),renderSignature='';
const audio=new SoftAudio();const offline=firstVisit?null:settle(state);if(!firstVisit)state.visits++;const refuge=new RefugeScene($('scene'),p=>$('load-progress').style.width=`${Math.round(p*100)}%`);
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2900);}
function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));$('save-warning').hidden=true;}catch{$('save-warning').hidden=false;}lastSave=Date.now();}
function savePrefs(){try{localStorage.setItem(PREF_KEY,JSON.stringify(prefs));}catch{}}
function isNight(){const h=new Date().getHours();return prefs.theme==='night'||prefs.theme==='auto'&&(h<7||h>=20);}
function updatePrefs(){const night=isNight();$('pocket').classList.toggle('night',night);$('pocket').classList.toggle('reduced',prefs.reduced);$('motion-setting').setAttribute('aria-checked',String(prefs.reduced));$('theme-setting').value=prefs.theme;$('day-badge').innerHTML=`${icon(night?'moon':'sun')}<span>${night?'Une nuit toute douce':'Un matin tranquille'}</span>`;refuge.sync(state,prefs);savePrefs();}
function sceneLevel(){const n=Object.values(state.levels).reduce((a,b)=>a+b,0);return n===0?'Un tout petit début':n<5?'Les premières pousses':n<12?'Un refuge qui s’éveille':n<25?'Un jardin bien entouré':'Un petit monde heureux';}
function showOffline(reward){if(!reward||reward.seconds<60||reward.amount<.1)return;if(document.querySelector('dialog[open]')){pendingOffline=reward;return;}$('offline-time').textContent=`Pendant ${duration(reward.seconds)}, votre refuge a fait naître de nouvelles lueurs.`;$('offline-amount').textContent='+'+format(reward.amount);$('offline-cap').textContent=reward.capped?`Moko garde jusqu’à ${offlineLimit(state)/3600} heures de lueurs. Elles sont déjà dans votre réserve.`:'Ces lueurs sont déjà dans votre réserve.';$('offline').showModal();}
function signature(){return JSON.stringify([activeTab,buyAmount,state.path,state.specs,state.cycles,state.roots,state.wishes,state.levels,state.friends,state.claimed,GARDEN.map(g=>state.earned>=g.unlock),FRIENDS.map(f=>state.earned>=f.unlock),MEMORIES.map(m=>m.value(state)>=m.goal)]);}
function renderCards(force=false){const sig=signature();if(!force&&sig===renderSignature)return;renderSignature=sig;const scroll=$('cards').scrollTop;
 if(activeTab==='garden'){$('section-eyebrow').textContent='CHAQUE PETIT GESTE COMPTE';$('section-title').textContent='Faire grandir le refuge';$('cards').setAttribute('aria-label','Améliorations du refuge');$('cards').innerHTML=GARDEN.map(g=>{const locked=state.earned<g.unlock;if(locked)return`<article class="upgrade-card locked-card"><div class="card-art">${icon(g.icon)}</div><div class="card-text"><h3>${g.name}</h3><p class="card-description">À ${format(g.unlock)} lueurs créées au total.</p></div><div class="locked-indicator">${icon('lock')}<span>${format(g.unlock)}</span></div></article>`;return`<article class="upgrade-card"><div class="card-art ${g.id}">${icon(g.icon)}</div><div class="card-text"><div class="card-title-line"><h3>${g.name}</h3><span class="card-level">NIV. ${state.levels[g.id]}</span></div><p class="card-description">${g.description}</p><p class="card-income">${icon('spark')} +${format(g.income*bonus(state)*permanentFactor(state)*growthFactor(state,g.id)*(1+Math.floor(state.levels[g.id]/10)*.5),true)} lueur${g.income*bonus(state)*permanentFactor(state)*growthFactor(state,g.id)*(1+Math.floor(state.levels[g.id]/10)*.5)>1?'s':''} / s par niveau</p></div><div class="card-cta"><button class="buy-button" data-buy="${g.id}" aria-label="Améliorer ${g.name}">${icon('spark')}<span>${format(price(state,g.id))}</span></button><small class="wait-label" data-wait="${g.id}"></small></div>${state.levels[g.id]>=5?state.specs[g.id]?`<div class="spec-label">${state.specs[g.id]==='lush'?'Floraison · production ×1,8':'Racines profondes · prix −30 %, production +25 %'}</div>`:`<div class="spec-choices"><span>Niveau 5 · un choix pour ce jardin</span><button data-spec="${g.id}" data-kind="lush" title="Production multipliée par 1,8">Floraison ×1,8</button><button data-spec="${g.id}" data-kind="patient" title="Prix réduits de 30 %, production +25 %">Racines −30 %</button></div>`:''}</article>`;}).join('');}
 if(activeTab==='friends'){$('section-eyebrow').textContent='IL RESTE TOUJOURS UNE PLACE';$('section-title').textContent='De la compagnie pour Moko';$('cards').setAttribute('aria-label','Compagnons du refuge');$('cards').innerHTML=FRIENDS.map(f=>{const owned=state.friends.includes(f.id),locked=state.earned<f.unlock;return`<article class="upgrade-card ${locked?'locked-card':''}"><div class="card-art ${f.id}">${icon(f.icon)}</div><div class="card-text"><div class="card-title-line"><h3>${f.name}</h3>${owned?'<span class="card-level">À LA MAISON</span>':''}</div><p class="card-description">${f.species}</p><p class="card-income">+${Math.round(f.bonus*100)} % de lueurs pour le refuge</p></div><div class="card-cta">${owned?`<button class="buy-button" disabled aria-label="${f.name} est au refuge">${icon('heart')}</button>`:locked?`<div class="locked-indicator">${icon('lock')}<span>${format(f.unlock)} créées</span></div>`:`<button class="buy-button" data-friend="${f.id}" aria-label="Inviter ${f.name}">${icon('spark')}<span>${format(f.cost)}</span></button><small class="wait-label" data-friend-wait="${f.id}"></small>`}</div></article>`;}).join('');}
 if(activeTab==='memories'){$('section-eyebrow').textContent='CE QUE LES BOIS NOUS APPRENNENT';$('section-title').textContent='Les jours dont on se souvient';$('cards').setAttribute('aria-label','Souvenirs de Moko');$('cards').innerHTML=MEMORIES.map(m=>{const complete=m.value(state)>=m.goal,claimed=state.claimed.includes(m.id);return`<article class="memory-card"><div class="memory-heading">${icon(claimed?'check':complete?'spark':'book')}<h3>${m.title}</h3><button class="memory-reward" data-memory="${m.id}" ${claimed||!complete?'disabled':''} aria-label="${claimed?'Souvenir conservé':'Recueillir le souvenir '+m.title}">${claimed?'Gardé':`${icon('spark')} +${format(m.reward)}`}</button></div><p>${complete?m.text:memoryHint(m.id)}</p><div class="memory-progress"><i data-progress="${m.id}"></i></div><div class="memory-meta"><span>${claimed?'Un souvenir à garder':complete?'Une petite attention vous attend':'Chaque jour, un peu plus près'}</span><span data-memory-value="${m.id}"></span></div></article>`;}).join('');}
 if(activeTab==='journey'){$('section-eyebrow').textContent='LES RACINES SE SOUVIENNENT';$('section-title').textContent='Une forêt sans fin';$('cards').setAttribute('aria-label','Voies, souhaits et renaissances');$('cards').innerHTML=journeyCards(state);}
 $('grow-tools').hidden=activeTab!=='garden';$('cards').scrollTop=scroll;updateButtons();}
function memoryHint(id){return{first:'Offrez à Moko sa toute première amélioration.',hundred:'Laissez le refuge créer 100 lueurs au fil du temps.',friend:'Invitez votre premier compagnon à rester au refuge.',five:'Prenez soin du jardin avec cinq améliorations.',thousand:'Laissez le temps faire naître 1 000 petites lueurs.',garden:'Accueillez une pousse de chaque sorte dans votre jardin.',family:'Faites une place à Noisette, Brume et Orme.'}[id];}
function updateButtons(){refreshJourney(state);const r=rate(state);document.querySelectorAll('[data-buy]').forEach(b=>{const id=b.dataset.buy,cost=price(state,id),max=false,afford=state.light+1e-9>=cost;b.disabled=max||!afford;const wait=document.querySelector(`[data-wait="${id}"]`);if(wait)wait.textContent=max?'Niveau maximum':afford?'Faire pousser':'Dans '+duration((cost-state.light)/r);});document.querySelectorAll('[data-friend]').forEach(b=>{const f=FRIENDS.find(f=>f.id===b.dataset.friend),afford=state.light+1e-9>=f.cost;b.disabled=!afford;document.querySelector(`[data-friend-wait="${f.id}"]`).textContent=afford?'Accueillir':'Dans '+duration((f.cost-state.light)/r);});for(const m of MEMORIES){const p=document.querySelector(`[data-progress="${m.id}"]`),v=document.querySelector(`[data-memory-value="${m.id}"]`);if(p)p.style.width=Math.min(100,m.value(state)/m.goal*100)+'%';if(v)v.textContent=`${format(Math.min(m.value(state),m.goal))} / ${format(m.goal)}`;}}
function updateUI(){const r=rate(state);$('pocket').dataset.tab=activeTab;$('pocket').dataset.path=state.path||'wild';$('pocket').dataset.season=season(state);$('journey-badge').textContent=journeyBadge(state);$('journey-badge').title='Les saisons changent tous les 20 niveaux de jardin.';$('balance').textContent=format(state.light);$('income').textContent='+'+format(r,true);$('level-chip').innerHTML=`${icon('leaf')}<span>${sceneLevel()}</span>`;const total=Object.values(state.levels).reduce((a,b)=>a+b,0);$('section-meta').textContent=activeTab==='journey'?`${format(state.roots)} racines`:activeTab==='garden'?`${total} pousse${total>1?'s':''}`:activeTab==='friends'?`${state.friends.length} / 3 amis`:`${state.claimed.length} / ${MEMORIES.length}`;$('friend-dot').hidden=!FRIENDS.some(f=>!state.friends.includes(f.id)&&state.earned>=f.unlock&&state.light>=f.cost);$('memory-dot').hidden=!MEMORIES.some(m=>!state.claimed.includes(m.id)&&m.value(state)>=m.goal);$('refuge-state').textContent=state.friends.length?'De petites vies, et une grande douceur.':'Et votre refuge grandit, tout doucement.';renderCards();updateButtons();}
function mutation(result,success){if(!result.ok){toast(result.reason);return;}save();refuge.sync(state,prefs);renderCards(true);updateUI();audio.chime();toast(success);}
$('cards').addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.path)mutation(choosePath(state,b.dataset.path),'Une nouvelle voie s’ouvre à Moko.');if(b.dataset.spec)mutation(specialize(state,b.dataset.spec,b.dataset.kind),'Cette pousse a trouvé sa vocation.');if(b.hasAttribute('data-wish'))mutation(claimWish(state),'Une racine éternelle. Un nouveau souhait.');if(b.hasAttribute('data-rebirth')){$('rebirth-description').textContent=rebirthDescription(state);$('rebirth-confirm').showModal();}if(b.dataset.buy){const g=GARDEN.find(g=>g.id===b.dataset.buy);mutation(buyMany(state,g.id,buyAmount),`${g.name} · le jardin s’épanouit.`);}if(b.dataset.friend){const f=FRIENDS.find(f=>f.id===b.dataset.friend);mutation(invite(state,f.id),`${f.name} se sent déjà chez lui.`);}if(b.dataset.memory){const m=MEMORIES.find(m=>m.id===b.dataset.memory);mutation(claim(state,m.id),`Un souvenir et ${format(m.reward)} petites lueurs.`);}});
$('rebirth-no').onclick=()=>$('rebirth-confirm').close();$('rebirth-yes').onclick=()=>{mutation(rebirth(state),'Un nouveau jardin. Les mêmes amis.');$('rebirth-confirm').close();};document.querySelectorAll('[data-amount]').forEach(b=>b.onclick=()=>{buyAmount=Number(b.dataset.amount);document.querySelectorAll('[data-amount]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(t=>{t.classList.toggle('active',t===b);if(t===b)t.setAttribute('aria-current','page');else t.removeAttribute('aria-current');});$('cards').scrollTop=0;renderCards(true);updateUI();});
$('pet').onclick=()=>{refuge.pet();$('heart-pop').classList.remove('show');void $('heart-pop').offsetWidth;$('heart-pop').classList.add('show');clearTimeout(heartTimer);heartTimer=setTimeout(()=>$('heart-pop').classList.remove('show'),1700);$('mood').textContent='Moko est heureux de vous voir.';audio.note(523.25,.4,.08);setTimeout(()=>{if($('mood').textContent==='Moko est heureux de vous voir.')$('mood').textContent=isNight()?'Moko écoute la nuit.':'Moko prend son temps.';},3300);};
async function toggleAudio(){try{const on=await audio.toggle();$('sound').innerHTML=icon(on?'sound':'mute');$('sound').setAttribute('aria-label',on?'Couper l’ambiance sonore':'Activer l’ambiance sonore');$('sound').setAttribute('aria-pressed',String(on));$('sound-setting').setAttribute('aria-checked',String(on));}catch{toast('Le son n’est pas disponible dans ce navigateur.');}}
$('sound').onclick=toggleAudio;$('sound-setting').onclick=toggleAudio;$('settings-open').onclick=()=>{$('settings').showModal();};$('settings-close').onclick=()=>$('settings').close();$('motion-setting').onclick=()=>{prefs.reduced=!prefs.reduced;updatePrefs();};$('theme-setting').onchange=e=>{prefs.theme=e.target.value;updatePrefs();};$('welcome-close').onclick=()=>{$('welcome').close();toast('Votre premier tapis de mousse vous attend.');};$('offline-close').onclick=()=>$('offline').close();document.querySelectorAll('dialog').forEach(d=>d.addEventListener('close',()=>{if(pendingOffline&&!document.querySelector('dialog[open]')){const r=pendingOffline;pendingOffline=null;showOffline(r);}}));
$('export-save').onclick=()=>{settle(state);save();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mon-refuge-moko.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('Une copie du refuge est prête.');};
$('import-save').onchange=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>100000){toast('Cette copie est trop volumineuse.');return;}try{const imported=parseSave(await file.text());if(!imported){toast('Ce fichier ne contient pas un refuge Moko Pocket valide.');return;}pendingImport=imported;$('settings').close();$('import-confirm').showModal();}catch{toast('Cette copie n’a pas pu être ouverte.');}};
$('import-confirm-no').onclick=()=>{pendingImport=null;$('import-confirm').close();};$('import-confirm-yes').onclick=()=>{if(!pendingImport)return;state=pendingImport;pendingImport=null;const r=settle(state);save();refuge.sync(state,prefs);renderCards(true);updateUI();$('import-confirm').close();toast('Votre petit monde est de retour.');showOffline(r);};
addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('install').hidden=false;});$('install').onclick=async()=>{if(!installPrompt)return;await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('install').hidden=true;};addEventListener('appinstalled',()=>{$('install').hidden=true;toast('Moko a trouvé sa place sur votre écran d’accueil.');});
document.addEventListener('visibilitychange',()=>{if(document.hidden){settle(state);save();}else{const r=settle(state);save();updatePrefs();updateUI();showOffline(r);}});addEventListener('pagehide',()=>{settle(state);save();});addEventListener('pageshow',e=>{if(e.persisted){const r=settle(state);save();updateUI();showOffline(r);}});
// Avoid simultaneous tabs producing or spending the same reserve independently.
addEventListener('storage',e=>{if(e.key!==SAVE_KEY||!e.newValue)return;const other=parseSave(e.newValue);if(other&&other.lastTick>=state.lastTick){state=other;refuge.sync(state,prefs);updateUI();}});
save();updatePrefs();renderCards(true);updateUI();
refuge.init().then(()=>{ready=true;$('loading').hidden=true;refuge.sync(state,prefs);if(firstVisit){$('welcome').showModal();firstVisit=false;}else showOffline(offline);}).catch(e=>{console.error(e);$('load-text').textContent='Moko n’a pas pu apparaître. Touchez ici pour réessayer.';$('loading').style.cursor='pointer';$('loading').onclick=()=>location.reload();toast('Le refuge continue de grandir. Rechargez pour retrouver la 3D.');});
setInterval(()=>{if(document.hidden)return;settle(state);updateUI();if(Date.now()-lastSave>5000)save();audio.tick(Date.now()/1000,isNight());},500);
const offlineStatus=document.createElement('p');offlineStatus.className='install-note';offlineStatus.id='offline-status';$('install-note').after(offlineStatus);
if(import.meta.env.PROD&&'serviceWorker'in navigator){offlineStatus.textContent='Le refuge se prépare pour vos prochaines visites hors ligne.';navigator.serviceWorker.register(import.meta.env.BASE_URL+'sw.js',{scope:import.meta.env.BASE_URL}).then(()=>navigator.serviceWorker.ready).then(()=>{offlineStatus.textContent='Le refuge est prêt à être retrouvé sans connexion.';console.info('Moko offline cache ready');}).catch(e=>{offlineStatus.textContent='Le mode hors ligne n’est pas disponible dans ce navigateur.';console.warn('Offline installation unavailable',e);});}else{offlineStatus.textContent=import.meta.env.PROD?'Ce navigateur ne propose pas le mode hors ligne.':'Le mode hors ligne sera disponible dans la version installable.';console.info('Moko offline support',import.meta.env.PROD,'serviceWorker'in navigator);}
