import {season} from './growth.js';
import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {clone as skeletonClone} from 'three/addons/utils/SkeletonUtils.js';
import {FRIENDS} from './economy.js';
const base=import.meta.env.BASE_URL;
const mat=(color,extra={})=>new T.MeshStandardMaterial({color,roughness:.92,...extra});
function addMesh(parent,geometry,material,x=0,y=0,z=0){const m=new T.Mesh(geometry,material);m.position.set(x,y,z);m.receiveShadow=true;parent.add(m);return m;}
export class RefugeScene{
 constructor(canvas,onProgress){this.canvas=canvas;this.onProgress=onProgress;this.time=0;this.last=0;this.lastRender=0;this.night=0;this.petUntil=0;this.friends=new Map();this.pending=new Set();this.state=null;this.ready=false;this.reduced=false;this.forceTheme='auto';this.error=null;this.loader=new GLTFLoader();this.assets={};}
 async init(){
  this.renderer=new T.WebGLRenderer({canvas:this.canvas,antialias:true,alpha:true,powerPreference:'low-power'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFShadowMap;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.22;this.renderer.setClearColor(0x000000,0);this.scene=new T.Scene();this.scene.fog=new T.Fog('#dce5d4',12,27);this.camera=new T.PerspectiveCamera(40,1,.1,60);this.camera.position.set(0,2.8,6.3);this.camera.lookAt(0,1.8,0);
  this.hemi=new T.HemisphereLight('#fff7de','#8aa47c',2.6);this.scene.add(this.hemi);this.sun=new T.DirectionalLight('#ffe6b5',2.2);this.sun.position.set(-3,8,5);this.sun.castShadow=true;this.sun.shadow.mapSize.set(1024,1024);Object.assign(this.sun.shadow.camera,{left:-6,right:6,top:7,bottom:-6,near:.2,far:20});this.sun.shadow.normalBias=.045;this.sun.shadow.bias=-.0004;this.scene.add(this.sun);const rim=new T.DirectionalLight('#d9edf0',1.4);rim.position.set(3,4,-4);this.scene.add(rim);
  this.hero=new T.Group();this.scene.add(this.hero);this.body=new T.Group();this.hero.add(this.body);this.garden=new T.Group();this.scene.add(this.garden);
  this.island=addMesh(this.garden,new T.CylinderGeometry(3.5,3.55,.22,64),mat('#a8be8c'),0,-.16,0);addMesh(this.garden,new T.CylinderGeometry(3.55,3.1,.5,64),mat('#b0b891'),0,-.50,0);
  const floor=addMesh(this.garden,new T.CircleGeometry(1.15,40),mat('#c6ceaa'),0,-.035,.15);floor.rotation.x=-Math.PI/2;
  const textureCanvas=document.createElement('canvas');textureCanvas.width=textureCanvas.height=64;const ctx=textureCanvas.getContext('2d'),g=ctx.createRadialGradient(32,32,0,32,32,32);g.addColorStop(0,'rgba(255,243,190,1)');g.addColorStop(.15,'rgba(255,223,139,.55)');g.addColorStop(1,'rgba(255,206,106,0)');ctx.fillStyle=g;ctx.fillRect(0,0,64,64);this.glowTex=new T.CanvasTexture(textureCanvas);
  const names=['tree_detailed','tree_oak','tree_small','mushroom_redGroup','flower_yellowC','flower_purpleA','grass_large','rock_smallA','plant_bush'];let done=0;const progress=()=>this.onProgress?.(++done/(names.length+1));
  await Promise.all([this.loader.loadAsync(base+'assets/character.glb').then(g=>{const model=g.scene,b=new T.Box3().setFromObject(model),size=b.getSize(new T.Vector3()),c=b.getCenter(new T.Vector3()),scale=2.7/size.y;model.scale.setScalar(scale);model.position.set(-c.x*scale,-b.min.y*scale,-c.z*scale);model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});const orientation=new T.Group();orientation.rotation.y=-Math.PI/2;orientation.add(model);this.body.add(orientation);progress();}),...names.map(async name=>{this.assets[name]=(await this.loader.loadAsync(base+'assets/nature/'+name+'.glb')).scene;progress();})]);
  this.canopy=[this.place('tree_detailed',-2.8,-2.3,3.1,.3),this.place('tree_oak',2.7,-2.8,3.5,-.3)];this.leaves=[];for(const tree of this.canopy)tree.traverse(o=>{if(o.isMesh){o.material=o.material.clone();const c=o.material.color;if(c.g>c.r*.9&&c.g>c.b*1.15)this.leaves.push(o.material);}});this.place('tree_small',-3.5,.2,1.6,.5);this.place('plant_bush',3,.4,.85);this.place('rock_smallA',1.1,.8,.27);this.place('flower_yellowC',-.9,.4,.35);this.place('flower_purpleA',1.5,-.4,.40);
  const presets=[[-2.2,1],[-1.7,1.7],[2.6,.2],[2,1.3],[-2,-1.2],[1.6,-1.4],[-1.7,-.4]];for(let i=0;i<presets.length;i++)this.place('grass_large',...presets[i],.35+(i%3)*.05,i*.7);
  this.moss=new T.Group();this.garden.add(this.moss);for(let i=0;i<12;i++){const a=i/12*Math.PI*2,r=1.4+(i%3)*.3;this.place('grass_large',Math.cos(a)*r,Math.sin(a)*r,.36,i*.5,this.moss);}
  this.mushrooms=new T.Group();this.garden.add(this.mushrooms);for(const[x,z]of [[-1.35,.9],[1.45,1.2],[-2.2,-.4]])this.place('mushroom_redGroup',x,z,.42,0,this.mushrooms);
  this.pond=new T.Group();this.garden.add(this.pond);const pond=addMesh(this.pond,new T.CircleGeometry(.6,40),mat('#89bfc0',{metalness:.15,roughness:.24}),1.6,.003,.25);pond.rotation.x=-Math.PI/2;pond.scale.set(1.35,.8,1);const ripple=addMesh(this.pond,new T.TorusGeometry(.39,.009,4,40),mat('#d2e4d4'),1.6,.01,.25);ripple.rotation.x=-Math.PI/2;
  this.lanterns=new T.Group();this.garden.add(this.lanterns);for(let i=0;i<5;i++){const x=-2.6+i*1.3,y=3.15-Math.sin(i/4*Math.PI)*.6;const bead=addMesh(this.lanterns,new T.SphereGeometry(.08,8,8),mat('#f0d59d',{emissive:'#e7ba65',emissiveIntensity:.8}),x,y,-1.8);const glow=this.glow(.65);this.lanterns.add(glow);glow.position.copy(bead.position);}
  const thread=new T.CatmullRomCurve3([new T.Vector3(-2.8,3.4,-1.8),new T.Vector3(0,2.6,-1.8),new T.Vector3(2.8,3.4,-1.8)]);addMesh(this.lanterns,new T.TubeGeometry(thread,24,.01,4,false),mat('#929c72'));
  this.fireflies=[];for(let i=0;i<20;i++){const p=this.glow(.05+(i%3)*.025);p.position.set(Math.sin(i*2.4)*2.5,.4+(i%7)*.35,Math.cos(i*2.4)*2);this.scene.add(p);this.fireflies.push({p,initial:p.position.clone(),phase:i*.7});}
  this.warmth=new T.PointLight('#ffdc9a',1,8,1.5);this.warmth.position.set(0,2,2);this.scene.add(this.warmth);
  this.blossoms=new T.Group();this.garden.add(this.blossoms);for(let i=0;i<18;i++){const a=i/18*Math.PI*2;this.place(i%2?'flower_purpleA':'flower_yellowC',Math.cos(a)*2.3,Math.sin(a)*1.5-.5,.25+(i%3)*.06,i,this.blossoms);}
  this.halo=addMesh(this.hero,new T.TorusGeometry(.47,.014,6,48),mat('#e9c883',{emissive:'#bd9b4c',emissiveIntensity:.4}),0,2.93,0);this.halo.rotation.x=Math.PI/2;this.halo.visible=false;
  this.moss.visible=this.mushrooms.visible=this.pond.visible=this.lanterns.visible=false;this.resize();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(this.canvas.parentElement);this.ready=true;this.renderer.setAnimationLoop(t=>this.frame(t));
 }
 glow(size){const s=new T.Sprite(new T.SpriteMaterial({map:this.glowTex,color:'#ffdf97',transparent:true,depthWrite:false,blending:T.AdditiveBlending}));s.scale.setScalar(size);return s;}
 place(name,x,z,h,rot=0,parent=this.garden){const o=this.assets[name].clone(true),b=new T.Box3().setFromObject(o),s=h/b.getSize(new T.Vector3()).y;o.scale.multiplyScalar(s);o.position.set(x,-b.min.y*s,z);o.rotation.y=rot;o.traverse(m=>{if(m.isMesh){m.castShadow=true;m.receiveShadow=true;}});parent.add(o);return o;}
 resize(){const r=this.canvas.parentElement.getBoundingClientRect();if(!r.width||!r.height)return;this.renderer.setSize(r.width,r.height,false);this.camera.aspect=r.width/r.height;this.camera.fov=r.height<330?43:40;this.camera.updateProjectionMatrix();}
 sync(state,prefs){this.state=state;this.reduced=prefs.reduced;this.forceTheme=prefs.theme;if(!this.ready)return;const colors=['#91ad78','#b3b977','#c58e62','#adbdc1'];this.island.material.color.set(colors[season(state)]);const leafColors=['#769566','#9d9e59','#b88056','#8da9a4'];for(const m of this.leaves)m.color.set(leafColors[season(state)]);this.blossoms.visible=state.path==='wild'||state.cycles>0;this.blossoms.scale.setScalar(1+Math.min(5,state.cycles||0)*.04);this.halo.visible=(state.roots||0)>0;this.halo.material.color.set(state.path==='stars'?'#d3b9eb':'#e9c883');this.pond.scale.setScalar(state.path==='water'?1.35:1);this.lanterns.scale.y=state.path==='stars'?1.1:1;this.moss.visible=state.levels.moss>0;this.mushrooms.visible=state.levels.mushrooms>0;this.pond.visible=state.levels.pond>0||state.path==='water';this.lanterns.visible=state.levels.lanterns>0||state.path==='stars';this.moss.scale.setScalar(1+Math.min(10,state.levels.moss)*.025);for(const f of FRIENDS)if(state.friends.includes(f.id))this.ensureFriend(f);for(const[id,a]of this.friends)a.root.visible=state.friends.includes(id);}
 async ensureFriend(f){if(this.friends.has(f.id)||this.pending.has(f.id))return;this.pending.add(f.id);try{const gltf=await this.loader.loadAsync(base+'assets/animals/'+f.model+'.glb');const model=skeletonClone(gltf.scene),box=new T.Box3().setFromObject(model),scale=(f.id==='fox'?.62:f.id==='deer'?1.05:1.4)/box.getSize(new T.Vector3()).y;model.scale.setScalar(scale);model.position.y=-box.min.y*scale;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});const root=new T.Group();root.add(model);this.scene.add(root);const mixer=new T.AnimationMixer(model),clip=gltf.animations.find(c=>c.name==='Idle')||gltf.animations[0];if(clip)mixer.clipAction(clip).play();this.friends.set(f.id,{root,mixer,phase:f.id==='fox'?0:f.id==='deer'?2.2:4.5});this.sync(this.state,{reduced:this.reduced,theme:this.forceTheme});}catch(e){console.error('Companion could not load',f.id,e);this.error=f.id;}finally{this.pending.delete(f.id);}}
 pet(){this.petUntil=this.time+2;}
 frame(now){if(document.hidden){this.last=now;return;}if(now-this.lastRender<32)return;this.lastRender=now;const dt=Math.min(.08,(now-(this.last||now))/1000);this.last=now;this.time+=dt;const t=this.time,pet=this.petUntil>t;const hours=new Date().getHours(),night=this.forceTheme==='night'||this.forceTheme==='auto'&&(hours<7||hours>=20);this.night=T.MathUtils.lerp(this.night,night?1:0,Math.min(1,dt*2));
  this.hemi.intensity=2.6-this.night*.95;this.sun.intensity=2.2-this.night*1.5;this.warmth.intensity=1+this.night*6;this.body.rotation.y=this.reduced?0:Math.sin(t*.25)*.06+(pet?Math.sin(t*3)*.12:0);this.body.rotation.z=this.reduced?0:Math.sin(t*.6)*.013;this.body.position.y=this.reduced?0:Math.sin(t*1.8)*.022+(pet?Math.abs(Math.sin(t*5))*.045:0);this.body.scale.y=1+(this.reduced?0:Math.sin(t*1.8)*.003);
  for(const[id,a]of this.friends){if(!a.root.visible)continue;const p=a.phase;const x=id==='fox'?-1.45:id==='deer'?1.7:-1.65,z=id==='fox'?.9:id==='deer'?.1:-1.15;a.root.position.set(x,0,z);a.root.rotation.y=id==='fox'?.45:-.5;if(!this.reduced)a.mixer.update(dt);}
  this.fireflies.forEach(({p,initial,phase})=>{p.material.opacity=.12+this.night*.45+(this.reduced?0:Math.sin(t*1.1+phase)*.12);if(!this.reduced){p.position.x=initial.x+Math.sin(t*.4+phase)*.14;p.position.y=initial.y+Math.sin(t*.65+phase)*.12;}});this.renderer.render(this.scene,this.camera);
 }
 dispose(){this.resizeObserver?.disconnect();this.renderer?.setAnimationLoop(null);this.renderer?.dispose();}
}

